pipeline {
  agent {
    node {
      label 'master'
    }
  }
  stages {
    stage('Checkout SCM') {
      steps {
        poll: false, url: 'git@hub.com:anup.dubey/nodejs-pipeline.git'
      }
    }
    stage('build docker images') {
      steps {
        sh '''docker build -t anuphnu/k8s-demo:$version .'''
      }
    }
    stage('login') {
    withDockerRegistry(credentialsId: '7eec2037-3218-4836-948a-9ae7375bfcae', url: 'https://index.docker.io/v1/') {
}
    }
    stage('push docker images') {
      steps {
        retry(2) {
            sh '''docker push anuphnu/k8s-demo:$version '''
        }
      }
    }
}
}
